openapi: 3.0.0
info: 
  title: testando documentação
  description: testando campo
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: servidor de teste

paths:
  /create:
    post:
      summary: cria um novo produto
      description: rota é responsável por cadastrar um novo produto
      tags:
        - product 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
            examples:
              product: 
                value:
                  name: "mouse"
                  category: "periférico"
                  brand: "multilaser"
                  price: 30
      responses:
        200:
          description: produto criado
          schema:
            $ref: "#/components/schemas/ProductResponse"
  /select/{id}:
    get:
      summary: Seleciona um produto para a camada de visualização
      description: Rota responsável por selecionar um produto com base no id
      tags:
        - produto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Produto selecionado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
          404:
            description: Produto não encontrado

              
components:
  schemas:
    Product:
      properties:
        name:
          type: string
        category:
          type: string
        brand:
          type: string
        price:
          type: number
        aelatorio:
          type: string
    ProductResponse:
      properties:
        id:
          type: number
        name:
          type: string
        category:
          type: string
        brand:
          type: string
        price:
          type: number
