openapi: 3.0.0
info: 
  title: testando documentação
  description: testando campo
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: servidor de teste

paths:
  /create:
    post:
      summary: cria um novo produto
      description: rota é responsável por cadastrar um novo produto
      tags:
        - product 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
            examples:
              product: 
                value:
                  name: "mouse"
                  category: "periférico"
                  brand: "multilaser"  
                  price: 30
      responses:
        200:
          description: produto criado
          schema:
            $ref: "#/components/schemas/ProductResponse"
  /select/{id}:
    get:
      summary: Seleciona um produto para a camada de visualização
      description: Rota responsável por selecionar um produto com base no id
      tags:
        - product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Produto selecionado com sucesso
          schema:
            $ref: "#/components/schemas/ProductResponse"
        404:
           description: Produto não encontrado
  /delete:
    delete:
      summary: rota responsavel por deletar um produto com base no id
      tags:
        - product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
      responses:
        200:
          description: produto deletado
          schema:
            $ref: "#/components/schemas/Product"
        404:
          description: produto não encontrado
  /update:
    post:
      summary: atualiza um produto com base no id
      tags:
        - product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductResponse"          
      responses:
        200:
          description: produto atualizado
          schema:
            $ref: "#/components/schemas/ProductResponse"
            



components:
  schemas:
    Product:
      properties:
        name:
          type: string
        category:
          type: string
        brand:
          type: string
        price:
          type: number
        aelatorio:
          type: string
    ProductResponse:
      properties:
        id:
          type: number
        name:
          type: string
        category:
          type: string
        brand:
          type: string
        price:
          type: number
